name: MineCoupon
version: 1.3
description: MineCoupon provides you a powerful coupon system.
author: Raith Thomas
webseite: http://www.rcraft.at

main: at.rcraft.minecoupon.MineCoupon

commands:
    mc:
        description: 'Main command of MineCoupon'
        usage: 'Usage: /mc <cuponcode> (<action> <args>)'
