name: MineCoupon
version: 3.3.5
description: MineCoupon provides you a powerful coupon system.
author: Raith Thomas
webseite: http://www.xtrsource.com

main: com.xtrsource.minecoupon.MineCoupon

commands:
    coupon:
        description: 'Main command of MineCoupon'
        usage: 'Usage: /coupon <cuponcode> (<action> <args>)'
